//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.06 at 07:33:19 PM PHT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.govtalk.gov.uk/taxation/PAYE/RTI/FullPaymentSubmission/15-16/1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.gov.govtalk.taxation.paye.rti.fullpaymentsubmission._15_16._1;
